import { IInjectedAssembly } from "../Common/IInjectedAssembly";

export const Actor_DestroyCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAWsRg0ErEQNCJRiAAIkQgABMEL//6RiAAKMmQEsAyAACAAAAAA=", 'base64');
export const Actor_SpawnCave: Buffer = Buffer.from("J73/wK+2ADCvswAkAAaxQDwTgA42c4Uwr7EAHAJ2iCGOJAAIr7IAIPe0ADivvwA0RIegAK+1ACyvtAAor7AAGBCAACcAoJAljiIAEFRAACUCdqAhliIAHDBDAAFQYAALjiMADIywHWAWAAAGAnYQIQwBmw4kBCegAECAJa5CHWACdhAhEAAADaxQABAwQgACEEAABgBkICMMAZsOAAAAAABAgCUQAAAFriIAEAwBmwQAAAAAAECAJa4iABASAABwAnaIIY4nAAyOJgAIjiUABI4kAAAMAzLur7AAEKIgAB4CdqAhjoIAFBBAAGM8EAABjoMAEI6RAAgAQxAhAFGII4YlAAgmBBekDAIFigJEICEEQQAFAECoJQwAlCsCgCAlEAAAVwAAgCWSIwACJAIABRRiAAcAAAAAAlCAIYIFHLwMAIGQAkAgJRRA//MAAAAADAGbBI4kAAwUQAAFAECAJQwAlCsCgCAlEAAARo+/ADQCdjAhkMIAHgIAICUkQgABoMIAHoezAFqXogBejiUADAAAMCUAE5wADAGNjAJimCWOJgAElicAAKIVAB6OIgAcjiUAEI4kABSOIwAYrgIBNDwCAAGuBQEorgQBLK4DATCuFAE4pgcAAK4GAAQCQhAhkEIcvMegAFCiAgADh6IAYuYAAAymAgAYx6AAVIeiAGbmFAAIpgIAHOYAABCuEwAUkiYAAiZEHCQMAJPmAgAoJTwDEjSMY1Z4lGIAAixEAMgQgAAJAAIQwABiECEkBAACrEQNBKxQDQiUYgACJEIAATBC//+kYgACPBGAEjYxDDiOMwAYAkAoJQwAg/cCACAlEAAAA64zABiUAgAIAAAANI+/ADSPtgAwj7UALI+0ACiPswAkj7IAII+xABzXtAA4AgAQJY+wABgD4AAIJ70AQA==", 'base64');
export const Actor_SpawnEntryCave: Buffer = Buffer.from("J73/6K+/ABQMAJVxAAAAADwEEjSMhFZ4lIMAAixlAMgQoAAJAAMYwACDGCEkBQADrGUNBKxiDQiUgwACJGMAATBj//+kgwACj78AFAPgAAgnvQAY", 'base64');
export const Actor_InitCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAGsRg0ErEQNCJRiAAIkQgABMEL//6RiAAIIAIP3AAAAAA==", 'base64');
export const Actor_SpawnWithParentAndCutsceneCave: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const Actor_SpawnWithAddress: Buffer = Buffer.from("J73/wK++ADivtwA0AAXxQDwXgA4294Uwr7EAHAL+iCGOIgAIr7UALK+0ACivswAkr7AAGK+/ADyPsABUr7YAMK+yACAAgJglAMCoJRBAACgA4KAljiMAEFRgACYC/pAhliMAHDBkAAFQgAAKjiQADI5iHWAUQAAFAv4YIQwBmw4kBCegrmIdYAL+GCEQAAALrGIAEDBjAAIQYAAFAIIgIwwBmw4AAAAAEAAABK4iABAMAZsEAAAAAK4iABAUQAAFAv6IITwC3q0kQgutEAAAXa4CAACOJwAMjiYACI4lAASOJAAADAMy7q+iABCiIAAeAv6QIY5CABQQQABQAAAAAI5DABCOUQAIAEMQIQBRiCM8AwABJGQXpIYlAAgMAgWKAmQgIQBAsCUEQQAHPAMAAQwAlCsCQCAlPALerTRC3q0QAABArgIAAJIkAAIkAgAFVIIABwL+GCECYxghgGUcvAwAgZACYCAlFED/8QL+GCGQYgAeAgAgJSRCAAGgYgAejiUADAwBjYwAADAlligAAI4mAASiFgAejiIAHI4lABCOJAAUjiMAGK4CATQ8AgABrhIBOKYIAACuBQEorgQBLK4DATCuBgAEAmIQIZBCHLwCACglogIAA4+iAFDGhAAAhEQAAIRDAALGggAExoAACIRCAASmBAAUpgMAFqYCABjmBAAI5gIADOYAABCmFQAckiYAAjwRgBI2MQw4DACT5iZkHCSOMgAYAmAoJQwAg/cCACAlEAAAA64yABiUAgAIAAAANI+/ADyPvgA4j7cANI+2ADCPtQAsj7QAKI+zACSPsgAgj7EAHI+wABgD4AAIJ70AQA==", 'base64');
export const Actor_SpawnTransitionActorCave: Buffer = Buffer.from("J73/0IeiAFLHoABEr6IAIIeiAFbnoAAUr6IAJIeiAE7HoABAr6IAHIeiAErnoAAQr6IAGK+/ACwMAJREAAAAADwEEjSMhFZ4lIMAAixlAMgQoAAJAAMYwACDGCEkBQAErGUNBKxiDQiUgwACJGMAATBj//+kgwACj78ALAPgAAgnvQAw", 'base64');
export const Actor_UpdateCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAasRg0ErEQNCJRiAAIkQgABMEL//6RiAAKMmQEwAyAACAAAAAA=", 'base64');
export const Object_SpawnCave: Buffer = Buffer.from("J73/4K+xABQ8ERI0jjFWeK+wABCWIgACr78AHCxGAMivsgAYAICAJRDAAAkAoBglAAIgwAIkECEkhA0EAiSIISQEAAesRA0EEAAAAqRFDQgAAIglkgUACAADMMAABREAPASADzSEj/AAhiAhAEUQIYySAASMhQAAAAIQgAICECGMRAAQAkWQI6RDAAwMAAN8AkAwJZIEAAgsgwASEGAADySCAAEABBkAAGQYIQADGIACAxghjGQAEAACGQAAkiAhAGIYIQADGIAkhAAPJBL/8AIDGCEAkiAkrGQAEDBCAP8AAhoAAEMYJaYDAAgSIAAGJEL//yQCAAEkAwABogIACAAAECWmIwAGj78AHI+yABiPsQAUj7AAEAPgAAgnvQAg", 'base64');
export const SkelAnime_DrawFlexLodCave: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const Sfx_Cave: Buffer = Buffer.from("PAKAHYxCoOQURAAYAAAYJTwGEjSMxlZ4JMQKBAAASCUkCAAKJAcAQAADEEAAQxAhAAIQgADCECGMQgoEFEgAAiRjAAEAgEglFGf/9ySEAAwRIAAGMKP/ACQCaAAQYgADJAIACq0iAAClJQAIA+AACAAAAAA=", 'base64');
export const SuperDynaPoly_AllocPolyList: Buffer = Buffer.from("PAISNIxCVngD4AAIrKIAAA==", 'base64');
export const SuperDynaSSNodeList_Alloc: Buffer = Buffer.from("PAJDIYxCVng8AxI0jGNWeIxCAACsowAArKIACAPgAAisoAAE", 'base64');
export const SuperDynaPoly_AllocVtxList: Buffer = Buffer.from("PAISNIxCVngD4AAIrKIAAA==", 'base64');
export const commandbuffer: Buffer = Buffer.from("J73/gIyCAASvtgBwr7UAbK+/AHyvvgB4r7cAdK+0AGivswBkr7IAYK+xAFyvsABYPBaAHDbWhKAAQPgJjtUcRDwIEjSNCFZ4lQIAADBC//8QQAJ7JB4AEAAAMCUkEQBAJBMAARAAAAIkFAACAuAwJQAAECUAAoBAAgKAIQAQgIABEBghjGMKBBRgAAQkQgABJhAKBBAAAAQBEIAhFFH/9gACgEAAAIAlAAYYgABmkCEAEpDAARKQIY5CAAQQQAJbJNcAAY5CAAQUUwA/AAAAABIAAD0AAAAAjkIABK4CAACOQgAIrgIABI5CACQQQAAVAAAAAJZFAAyWRgAOjkMAJAEeECEnxwAIAAY0AAAFLAABBzghr6IAEK+jABQABjQDPASAHDSEhKAMyESNAAUsA45CACQ8CBI0jQhWeBAAAjquAgAIlkYADI5HABjGQAAcxkIAIJZCABCWQwASlkQAFJZFAA4AAhQAAAMcAAAEJAAABSwAAAIUAwADHAMABCQDAAUsAwAGNACvpQAkr6QAIK+jAByvogAY56IAFOegABA8BYAcNKWEoDwEgBw0hKDEDACURAAGNAM8CBI0jQhWeBAAAhmuAgAIjkIABBRUACUAZhAhAAIQwAECECGUQwAQMGP//xRgAAoAAAAAjEYADDwFgBw0paDEPASAHAwAk/g0hISgPAgSNBAAAgeNCFZ4lEMAEIxFAAwwY///FHMACQAAAACURgASPASAHDSEoMQMAJPmMMYA/zwIEjQQAAH6jQhWeDwGgBw0xoSgPASAHAwAlZI0hKDEPAgSNBAAAfKNCFZ4jkIABCQHAAMURwAKAGYQIQACEMABAhAhjEQADIxFABAMAzI8jEYAFDwIEjQQAAHljQhWeI5CAAQkCQAEFEkACwBmECEAAhDAAQIQIZRFAAw8BIAcNISEoAwBvtQwpf//PAgSNBAAAdeNCFZ4jkQABCQCAAUUggAUAGYQIQACEMABAhAhlEQADCfDABiQRgAcJ8IAFAEDGCEBAhAhJ8cAEAEHOCEBHighr6MAFK+iABAwxgD/DAMgGzCE//88CBI0EAABwI0IVniORAAEJAIABxSCADoAZhAhAAIQwAECECGMSgAQjEIADDwQgB02EISgAAAgJaYCHhokBQAFJAIAFK+mAFCvowBMr6gASDwBgBKkKrniDAGO/KICHhWvogBAj6QAQI+oAEiPowBMj6YAUBCAABYAABAlj6IAQBBTABMkAgABj6IAQBBUABAkAgAEj6IAQCQHAAMQRwAMJAIABY+iAEAkCQAEUEkACCQCACCPpQBAJAQABRSkAAQAABAlEAAAAiQCACwkAgAEAGYYIQADGMCiAh5eAQMQIYxEABQkA///PAgSNBCDAYaNCFZ4jEIAFBAAAYOiAh3ojkQABCQCAAgUggA1AAAAABIAAZYAAAAAAGYYIQADGMABAxghjGIADBBVAXcAAAAAjGkADI6iBnwmqAAwhqYAHIalAACuoAEwrqABNCanACSsQAEwrEABNDwEgBw0hISgr6gAEK+pABQMyESNr6MASDwFgBw0paDEPASAHDSEhKAMAJP4jqYGfDwFgBw0paDEPASAHDSEhKAMAJP4AqAwJQwBmySOpAZ8DAGbJAKgICWPowBIPAgSNI0IVniMdQAMjkIABK4CAACOQgAIrgIABK4VAAiu1QJwEAABS67VAoiORAAEJAIACRSCAPwAAAAAEgAA+gAAAACORAAEAGYQIa4EAACORAAIAAIQwK4EAAQBAhAhjEQAFBSAAAgAAAAAjEIADABA+AkAAAAAPAgSNI0IVngQAAE0rgMACIxCABQUUwAMAGYQIQACEMABAhAhjEMADIxCABCMRQAEAGD4CYxEAAA8CBI0jQhWeBAAASauAwAIAAIQwAECECGMQwAUFHQADQAAAACMQwAMjEQAEIxCABCMhQAEjEcADIyEAAAAYPgJjEYACDwIEjSNCFZ4EAABFa4DAAiMRAAUJAMAAxSDABIAAAAAjEgADIxDABCMRAAQjEIAEIyHAAyMhgAIjGUABIxkAACMQwAUjEIAEK+jABQBAPgJr6IAEDwIEjSNCFZ4EAABAK4DAAiMRAAUJAMABBSDABcAAAAAjEgADIxEABCMQwAQjEkAEIxCABCMZwAMjGYACIxDAByMQgAYjIUABIyEAACvowAcr6IAGI0jABSNIgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAADmrgMACIxEABQkAwAFFIMAHAAAAACMSAAMjEQAEIxDABCMSQAQjEoAEIxCABCMZwAMjGYACIxDACSMQgAgjIUABIyEAACvowAkr6IAII1DAByNQgAYr6MAHK+iABiNIwAUjSIAEK+jABQBAPgJr6IAEDwIEjSNCFZ4EAAAx64DAAiMRAAUJAMABhSDACEAAAAAjEgADIxEABCMQwAQjEkAEIxKABCMSwAQjEIAEIxnAAyMZgAIjEMALIxCACiMhQAEjIQAAK+jACyvogAojWMAJI1iACCvowAkr6IAII1DAByNQgAYr6MAHK+iABiNIwAUjSIAEK+jABQBAPgJr6IAEDwIEjSNCFZ4EAAAo64DAAiMRAAUJAMABxSDACYAAAAAjEgADIxEABCMQwAQjEkAEIxKABCMSwAQjEwAEIxCABCMZwAMjGYACIxDADSMQgAwjIUABIyEAACvowA0r6IAMI2DACyNggAor6MALK+iACiNYwAkjWIAIK+jACSvogAgjUMAHI1CABivowAcr6IAGI0jABSNIgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAAB6rgMACIxEABQkAwAIFIMAdgAAAACMSAAMjEQAEIxDABCMSQAQjEoAEIxLABCMTAAQjE0AEIxCABCMZwAMjGYACIxDADyMQgA4jIUABIyEAACvowA8r6IAOI2jADSNogAwr6MANK+iADCNgwAsjYIAKK+jACyvogAojWMAJI1iACCvowAkr6IAII1DAByNQgAYr6MAHK+iABiNIwAUjSIAEK+jABQBAPgJr6IAEDwIEjSNCFZ4EAAATK4DAAiORAAEJAIACxSCAA8AZhAhAAIQwAECECGQRAAMkqMEmaKkCJCURAAOkEUADTRjAAKipQiRoqMEmYxCABimpAiSEAAAOq6iBJCORAAEJAIADBSCACAAAAAAEgAASwBmECEAAhDAAQIQIYxDAAwQYAAUAAAAAI5DAASuAwAAjkMACK4DAASMQwAMFHQAB4xEABAMAZsOAAAAADwIEjSNCFZ4EAAAIq4CAAgMAZsEAAAAADwIEjSNCFZ4EAAAHK4CAAgMAZskjEQAEDwIEjQQAAAXjQhWeI5EAAQkAgANFIIAEwAAAAASAAARAAAAAI5EAAQAZhAhrgQAAI5DAAgAAhDAAQIQIa4DAASURQAMPASAHTSEnEQABSwADAIEvAAFLAM8CBI0jQhWeK4CAAiuQAAElQIAADBC//8C4hArFED9jCfeACilAAAAlQIAAiQDAMgwQv//VEMAEI+/AHylAAACAAAwJSQFBkAMAY2MJQQNBDwCEjSMQlZ4JAMACKxDDQQQAAAFj78AfBAA/+iOQgAEEAD/m45CAASPvgB4j7cAdI+2AHCPtQBsj7QAaI+zAGSPsgBgj7EAXI+wAFgD4AAIJ70AgA==", 'base64');
export const commandbuffer_offsets: Buffer = Buffer.from("", 'base64');

class OOTAssembly implements IInjectedAssembly {
    Actor_DestroyCave: Buffer = Actor_DestroyCave;
    Actor_InitCave: Buffer = Actor_InitCave;
    Actor_SpawnCave: Buffer = Actor_SpawnCave;
    Actor_SpawnTransitionActorCave: Buffer = Actor_SpawnTransitionActorCave;
    Actor_SpawnEntryCave: Buffer = Actor_SpawnEntryCave;
    Actor_SpawnWithAddress: Buffer = Actor_SpawnWithAddress;
    commandbuffer: Buffer = commandbuffer;
    Object_SpawnCave: Buffer = Object_SpawnCave;
    Actor_UpdateCave: Buffer = Actor_UpdateCave;
    Actor_SpawnWithParentAndCutsceneCave!: Buffer;
    Sfx_Cave: Buffer = Sfx_Cave;

    VERSIONS: Map<number, Map<string, number>> = new Map([
        [
            0,
            new Map<string, number>([
                ["Actor_DestroyCave", 0x80021104],
                ["Actor_InitCave", 0x800253c8],
                ["Actor_SpawnEntryCave", 0x80023de8],
                ["Actor_SpawnTransitionActorCave", 0x8002557c],
                ["Actor_UpdateCave", 0x800240d8],
                ["Actor_SpawnCave", 0x80025110],
                ["CommandBuffer_Update", 0x800a0bf8],
                ["Object_SpawnCave", 0x800812F0],
                ["SuperDynaPoly_AllocPolyList", 0x8003133C],
                ["SuperDynaPoly_AllocVtxList", 0x80031358],
                ["SuperDynaSSNodeList_Alloc", 0x80031378]
            ]),
        ],
    ]);
}

export const OOTAssemblyBuffers: IInjectedAssembly = new OOTAssembly();