package:
  name: z64lib-nightly
  version: {{ environ.get('MYPKG_VERSION', '') }}

source:
  fn: Z64Lib.zip
  url: ../dist/Z64Lib.zip

build:
  number: {{ environ.get('MYPKG_BUILD', '') }}
  binary_relocation: False
  detect_binary_files_with_prefix: False
  noarch: generic
  include_recipe: False
  
requirements:
  run:
    - mips-assembler

about:
  home: http://modloader64.com
  license: GPL-3
  summary: Zelda64 Library for ML64