import { IInjectedAssembly } from "../Common/IInjectedAssembly";

export const Actor_DestroyCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAWsRg0ErEQNCJRiAAIkQgABMEL//6RiAAKMmQE0AyAACAAAAAA=", 'base64');
export const Actor_SpawnEntryCave: Buffer = Buffer.from("J73/6K+/ABQMAuy0AAAAADwEEjSMhFZ4lIMAAixlAMgQoAAJAAMYwACDGCEkBQADrGUNBKxiDQiUgwACJGMAATBj//+kgwACj78AFAPgAAgnvQAY", 'base64');
export const Actor_SpawnCave: Buffer = Buffer.from("J73/wK+3ACyvswAcl6IAWq+/ADSvvgAwr7YAKK+1ACSvtAAgr7IAGK+xABSvsAAQ97QAOJepAF6QiAAOAAIUACQDAP+HtwBiFQMAAwBJmCUQAAB4AACAJQCgoCUAwCglRIegAACAqCUMAus1AMCQJRBAAB4AQIglPAQAAYRFAAgkhH2IDAS9ggKEICEEQQADAECwJRAAABEAEpFAkiMAAiQCAAVUYgATjiQADDwCAAICghAhgEWG4AwC1zECgCAlUEAADI4kAAyGIwAAJAIBLVBiAAiOJAAMABKRQDwEgBo0hO/QDALq/wCSICEQAABRAACAJQwECxgAEpFAPASAGjSE79AAQIAlEED/9gCS8CGPwgAIUEAABY4lAAyTwgAeJEIAAaPCAB6OJQAMDAIljAIAICWGIgAAjiQABCQDAAOuHgFApgIAABRDAAWuBAAEABe2AAAWtgMQAAADAAC4JQAWtgAAFrYDohYAHo4iAByOJQAQjiQAFI4jABiuAgE8PAIAAq4FATCuBAE0rgMBOAKCECGQQobgx6AAUKICAAOPogBk5gAADKYCABzHoABUJAL//6ICADgkAgP/pgIAIOYUAAjmAAAQrhMAFKYXABiSJgACAqAgJQwC6q0CACglPAMSNIxjVniUYgACLEQAyBCAAAkAAhDAAGIQISQEAAKsRA0ErFANCJRiAAIkQgABMEL//6RiAAI8EYAfNjGBgI4yABgCgCglDALaDQIAICWuMgAYj78ANI++ADCPtwAsj7YAKI+1ACSPtAAgj7MAHI+yABiPsQAU17QAOAIAECWPsAAQA+AACCe9AEA=", 'base64');
export const Actor_InitCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAGsRg0ErEQNCJRiAAIkQgABMEL//6RiAAIIAtoNAAAAAA==", 'base64');
export const Actor_SpawnWithAddress: Buffer = Buffer.from("J73/qK+3ADSvtgAwr7MAJK+wABj3uABQ97YASJeiAHKvvwA8r74AOK+1ACyvtAAor7IAIK+xABz3tABAl6kAdpCIAA4AAhQAJAMA/8e4AGjHtgBsh7YAeo+3AHyPsACAEQMAfwBJmCUAoKglAMAoJUSHoAAAgKAlDALrNQDAkCUQQAB3AECIJTwEAAGERQAIJIR9iAwEvYICpCAhBEEAAwBA8CUQAAAQABKRQJIjAAIkAgAFVGIAHgASkUA8AgACAqIQIYBFhuAMAtcxAqAgJRBAABcAEpFAhiMAACQCAS0QYgATAAAAADwEgBo0hO/Qj78API++ADiPtwA0j7YAMI+1ACyPtAAoj7MAJI+xAByPsAAY17gAUNe2AEjXtABAAJIgIY+yACAIAur/J70AWDwEgBo0hO/QEgD/7QCSECGMQwAIUGAABY4lAAyQQwAeJGMAAaBDAB6OJQAMAgAgJQwCJYyvogAQhiMAAI4lAASPogAQJAQAA64CAUCmAwAAFGQABa4FAAQAFvYAAB72AxAAAAMAALAlAB72AAAe9gOiHgAejiIAHI4lABCOJAAUjiMAGK4CATw8AgACrgUBMK4EATSuAwE4AqIQIZBChuDmFAAIogIAAyQC//+iAgA4JAID/6YCACDmGAAM5hYAEK4TABSmFgAYphcAHJImAAICgCAlDALqrQIAKCU8AxI0jGNWeJRiAAIsRADIEIAACQACEMAAYhAhJAQAAqxEDQSsUA0IlGIAAiRCAAEwQv//pGIAAjwRgB82MYGAjjIAGAKgKCUMAtoNAgAgJa4yABiPvwA8j74AOI+3ADSPtgAwj7UALI+0ACiPswAkj7IAII+xAByPsAAY17gAUNe2AEjXtABAA+AACCe9AFg=", 'base64');
export const Actor_SpawnTransitionActorCave: Buffer = Buffer.from("J73/oK+1AFQ8FQACr7AAQACVqCGvvwBcr7YAWK+0AFCvswBMr7IASK+xAEQ8AkM2kqOHYCRCC2GOsIdkr6IAOBBgAFgAgLAlAKCgJQAAiCUkEgP/JBMABIYGAAQEwgBOJjEAAYICAAAEQgAIggIAAoKkhuBQggAOlgMADIKkhvRQggALlgMADIICAAIEQgBCJjEAAYKkhuBQggAFlgMADIKkhvRUggA8JjEAAZYDAAzHogA4AAMRwkSCAAAwYwB/RoAAIEYCAAKGBwAGr6AAMK+yACyvowAoRgAADZYDAA5EAgAAABEigDBjA/8AAhQAAGQYIQACFANEhwAAr6MAJK+gACCvogAcr6AAGIYCAApGgAAgRAcAAESCAAAwxh//RoAAIOegABSGAgAIAsAoJUSCAAACgCAlRoAAIAwC64XnoAAQVEAAA5YDAAQQAAARkqOHYDwFEjSMpVZ4AAMYI6YDAASUpAACLIYAyBDAAAmSo4dgAAQgwACkICGskw0ErIINCJSiAAIkQgABMEL//6SiAAImMQABAiMQKhRA/64mEAAQj78AXI+2AFiPtQBUj7QAUI+zAEyPsgBIj7EARI+wAEAD4AAIJ70AYA==", 'base64');
export const Actor_SpawnWithParentAndCutsceneCave: Buffer = Buffer.from("J73/wK++ADCvtgAor7IAGK+/ADSXsgBar7cALK+1ACSvtAAgr7MAHK+xABSvsAAQ97QAOJeoAF6QgwAOABKUACQCAP+HvgBij7YAcBRiAAMCSJAlEAAAhAAAgCUAoJglAMAoJUSHoAAAgKAlDALrNQDAgCUQQAAbAECIJTwEAAGERQAIJIR9iAwEvYICZCAhBEEAAwBAqCUQAAAOABAhQJIjAAIkAgAFFGIAEDwCAAICYhAhgEWG4AwC1zECYCAlEEAACiQCAS2GIwAAEGIABwAQIUA8A4AaNGPv0AwC6v8AZCAhEAAAYAAAgCUMBAsYjiQADAAQIUA8A4AaNGPv0ABAgCUQQP/1AGS4IY7jAAhQYAAFjiUADJLjAB4kYwABouMAHo4lAAwMAiWMAgAgJYYjAACOJQAEJAQAA64XAUCmAwAAFGQABa4FAAQAHq4AABWuAxAAAAMAAPAlABWuAAAVrgOiFQAejiUAEI4kABSOIwAYjiIAHK4FATCuBAE0rgMBOBLAAAauAgE8gsIAA64WASCiAgADEAAABa7QASQ8AgACAmIQIZBChuCiAgADx6AAUI+iAGiPpABk5gAADMegAFQwQgB/JAMAf+YUAAjmAAAQrhIAFKYeABgUQwACpgQAHCQC//+iAgA4j6IAbBRAAAQCgCAlJAID/6+iAGyPogBspgIAIJImAAIMAuqtAgAoJTwDEjSMY1Z4lGIAAixEAMgQgAAJAAIQwABiECEkBAACrEQNBKxQDQiUYgACJEIAATBC//+kYgACPBGAHzYxgYCOMgAYAmAoJQwC2g0CACAlrjIAGI+/ADSPvgAwj7cALI+2ACiPtQAkj7QAII+zAByPsgAYj7EAFNe0ADgCABAlj7AAEAPgAAgnvQBA", 'base64');
export const Actor_UpdateCave: Buffer = Buffer.from("PAMSNIxjVniUYgACLEYAyBDAAAkAAhDAAGIQISQGAAasRg0ErEQNCJRiAAIkQgABMEL//6RiAAKMmQE4AyAACAAAAAA=", 'base64');
export const Object_SpawnCave: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const Sfx_Cave: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const SkelAnime_DrawFlexLodCave: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const SuperDynaPoly_AllocPolyList: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const SuperDynaSSNodeList_Alloc: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const SuperDynaPoly_AllocVtxList: Buffer = Buffer.from("A+AACAAAAAA=", 'base64');
export const commandbuffer: Buffer = Buffer.from("J73/gIyCAASvtgBwr7UAbK+/AHyvvgB4r7cAdK+0AGivswBkr7IAYK+xAFyvsABYPBaAPjbWayAAQPgJjtUczDwIEjSNCFZ4lQIAADBC//8QQAKhJB4AEAAAMCUkEQBAJBMAARAAAAIkFAACAuAwJQAAECUAAoBAAgKAIQAQgIABEBghjGMKBBRgAAQkQgABJhAKBBAAAAQBEIAhFFH/9gACgEAAAIAlAAYYgABmkCEAEpDAARKQIY5CAAQQQAKBJNcAAY5CAAQUUwBtAAAAABIAAGsAAAAAjkIABK4CAACOQgAIrgIABJZCABYAAhQAAAIUAxRTACoAAAAAlkYADI5HABjGQAAcxkIAIJZCABCWQwASlkQAFJZFAA6WSAAolkkAKgACFACOSgAkAAMcAAAEJAAABSwAMQj//wACFAMAAxwDAAQkAwAFLAMxKf//AAY0AK+oACivpQAkr6QAIK+qADCvqQAsr6MAHK+iABjnogAU56AAEDwFgD40pWsgPASAPjSEh8AMAuuFAAY0AzwIEjSNCFZ4EAACSa4CAAiOQgAkEEAAFQAAAACWRQAMlkYADo5DACQBHhAhJ8cACAAGNAAABSwAAQc4Ia+iABCvowAUAAY0AzwEgD40hGsgDMhEjQAFLAOOQgAkPAgSNI0IVngQAAIyrgIACJZGAAyORwAYxkAAHMZCACCWQgAQlkMAEpZEABSWRQAOAAIUAAADHAAABCQAAAUsAAACFAMAAxwDAAQkAwAFLAMABjQAr6UAJK+kACCvowAcr6IAGOeiABTnoAAQPAWAPjSlayA8BIA+NISHwAwC6xgABjQDPAgSNI0IVngQAAIRrgIACI5CAAQUVAAlAGYQIQACEMABAhAhlEMAEDBj//8UYAAKAAAAAIxGAAw8BYA+NKWHwDwEgD4MAurJNIRrIDwIEjQQAAH/jQhWeJRDABCMRQAMMGP//xRzAAkAAAAAlEYAEjwEgD40hIfADALqrTDGAP88CBI0EAAB8o0IVng8BoA+NMZrIDwEgD4MAu0mNISHwDwIEjQQAAHqjQhWeI5CAAQkBwADFEcACgBmECEAAhDAAQIQIYxEAAyMRQAQDAISaIxGABQ8CBI0EAAB3Y0IVniOQgAEJAkABBRJAAsAZhAhAAIQwAECECGURQAMPASAPjSEayAMBErQMKX//zwIEjQQAAHPjQhWeI5EAAQkAgAFFIIAFABmECEAAhDAAQIQIZREAAwnwwAYkEYAHCfCABQBAxghAQIQISfHABABBzghAR4oIa+jABSvogAQMMYA/wwGfDIwhP//PAgSNBAAAbiNCFZ4jkQABCQCAAcUggA4AGYQIQACEMABAhAhjEIADDwQgEA2EGsgAAAgJaYCiHokBQAFJAIAFK+mAFCvowBMr6gASAwD/RSiAoh1r6IAQI+kAECPqABIj6MATI+mAFAQgAAWAAAQJY+iAEAQUwATJAIAAY+iAEAQVAAQJAIABI+iAEAkBwADEEcADCQCAAWPogBAJAkABFBJAAgkAgAgj6UAQCQEAAUUpAAEAAAQJRAAAAIkAgAsJAIABABmGCEAAxjAogKIfwEDECGMRAAUJAP//zwIEjQQgwGBjQhWeIxCABQ8AYAfEAABfaAi9pCORAAEJAIACBSCADUAAAAAEgABkAAAAAAAZhghAAMYwAEDGCGMYgAMEFUBcQAAAACMaQAMjqIKgCaoADCGpgAchqUAAK6gATiuoAE8JqcAJKxAATisQAE8PASAPjSEayCvqAAQr6kAFAzIRI2vowBIPAWAPjSlh8A8BIA+NIRrIAwC6smOpgqAPAWAPjSlh8A8BIA+NIRrIAwC6skCoDAlDAQLOI6kCoAMBAs4AqAgJY+jAEg8CBI0jQhWeIx1AAyOQgAErgIAAI5CAAiuAgAErhUACK7VArAQAAFFrtUCyI5EAAQkAgAJFIIA/AAAAAASAAD6AAAAAI5EAAQAZhAhrgQAAI5EAAgAAhDArgQABAECECGMRAAUFIAACAAAAACMQgAMAED4CQAAAAA8CBI0jQhWeBAAAS6uAwAIjEIAFBRTAAwAZhAhAAIQwAECECGMQwAMjEIAEIxFAAQAYPgJjEQAADwIEjSNCFZ4EAABIK4DAAgAAhDAAQIQIYxDABQUdAANAAAAAIxDAAyMRAAQjEIAEIyFAASMRwAMjIQAAABg+AmMRgAIPAgSNI0IVngQAAEPrgMACIxEABQkAwADFIMAEgAAAACMSAAMjEMAEIxEABCMQgAQjIcADIyGAAiMZQAEjGQAAIxDABSMQgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAAD6rgMACIxEABQkAwAEFIMAFwAAAACMSAAMjEQAEIxDABCMSQAQjEIAEIxnAAyMZgAIjEMAHIxCABiMhQAEjIQAAK+jAByvogAYjSMAFI0iABCvowAUAQD4Ca+iABA8CBI0jQhWeBAAAOCuAwAIjEQAFCQDAAUUgwAcAAAAAIxIAAyMRAAQjEMAEIxJABCMSgAQjEIAEIxnAAyMZgAIjEMAJIxCACCMhQAEjIQAAK+jACSvogAgjUMAHI1CABivowAcr6IAGI0jABSNIgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAADBrgMACIxEABQkAwAGFIMAIQAAAACMSAAMjEQAEIxDABCMSQAQjEoAEIxLABCMQgAQjGcADIxmAAiMQwAsjEIAKIyFAASMhAAAr6MALK+iACiNYwAkjWIAIK+jACSvogAgjUMAHI1CABivowAcr6IAGI0jABSNIgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAACdrgMACIxEABQkAwAHFIMAJgAAAACMSAAMjEQAEIxDABCMSQAQjEoAEIxLABCMTAAQjEIAEIxnAAyMZgAIjEMANIxCADCMhQAEjIQAAK+jADSvogAwjYMALI2CACivowAsr6IAKI1jACSNYgAgr6MAJK+iACCNQwAcjUIAGK+jAByvogAYjSMAFI0iABCvowAUAQD4Ca+iABA8CBI0jQhWeBAAAHSuAwAIjEQAFCQDAAgUgwBwAAAAAIxIAAyMRAAQjEMAEIxJABCMSgAQjEsAEIxMABCMTQAQjEIAEIxnAAyMZgAIjEMAPIxCADiMhQAEjIQAAK+jADyvogA4jaMANI2iADCvowA0r6IAMI2DACyNggAor6MALK+iACiNYwAkjWIAIK+jACSvogAgjUMAHI1CABivowAcr6IAGI0jABSNIgAQr6MAFAEA+AmvogAQPAgSNI0IVngQAABGrgMACI5EAAQkAgALFIIACQBmECGSpAUpAAIQwDSDAAKiowUpAQIQIYxCABgQAAA6rqIFII5EAAQkAgAMFIIAIAAAAAASAABLAGYQIQACEMABAhAhjEMADBBgABQAAAAAjkMABK4DAACOQwAIrgMABIxDAAwUdAAHjEQAEAwECyIAAAAAPAgSNI0IVngQAAAirgIACAwECxgAAAAAPAgSNI0IVngQAAAcrgIACAwECziMRAAQPAgSNBAAABeNCFZ4jkQABCQCAA0UggATAAAAABIAABEAAAAAjkQABABmECGuBAAAjkMACAACEMABAhAhrgMABJRFAAw8BIA/NIToqAAFLAAMBLy4AAUsAzwIEjSNCFZ4rgIACK5AAASVAgAAMEL//wLiECsUQP1mJ94AKKUAAACVAgACJAMAyDBC//9UQwAQj78AfKUAAAIAADAlJAUGQAwD+zAlBA0EPAISNIxCVngkAwAIrEMNBBAAAAWPvwB8EAD/6I5CAAQQAP+hjkIABI++AHiPtwB0j7YAcI+1AGyPtABoj7MAZI+yAGCPsQBcj7AAWAPgAAgnvQCA", 'base64');

export class MMAssembly implements IInjectedAssembly {
    Actor_DestroyCave: Buffer = Actor_DestroyCave;
    Actor_InitCave: Buffer = Actor_InitCave;
    Actor_SpawnCave: Buffer = Actor_SpawnCave;
    Actor_SpawnTransitionActorCave: Buffer = Actor_SpawnTransitionActorCave;
    Actor_SpawnEntryCave: Buffer = Actor_SpawnEntryCave;
    Actor_SpawnWithParentAndCutsceneCave: Buffer = Actor_SpawnWithParentAndCutsceneCave;
    Actor_SpawnWithAddress: Buffer = Actor_SpawnWithAddress;
    commandbuffer: Buffer = commandbuffer;
    Object_SpawnCave: Buffer = Object_SpawnCave;
    Actor_UpdateCave: Buffer = Actor_UpdateCave;
    Sfx_Cave!: Buffer;
    VERSIONS: Map<number, Map<string, number>> = new Map([
        [
            0,
            new Map<string, number>([
                ["Actor_DestroyCave", 0x800B6968],
                ["Actor_InitCave", 0xDEADBEEF],
                ["Actor_SpawnEntryCave", 0x800B92D8],
                ["Actor_SpawnEntryCave2", 0x800B9430],
                ["Actor_SpawnTransitionActorCave", 0x800BB140],
                ["Actor_UpdateCave", 0x800B9744],
                ["Actor_SpawnCave", 0x800BAC60],
                ["Actor_SpawnWithParentAndCutsceneCave", 0x800BAE14],
                ["CommandBuffer_Update", 0x801737A0],
                ["Object_SpawnCave", 0xDEADBEEF],
                ["SuperDynaPoly_AllocPolyList", 0xDEADBEEF],
                ["SuperDynaPoly_AllocVtxList", 0xDEADBEEF],
                ["SuperDynaSSNodeList_Alloc", 0xDEADBEEF]
            ]),
        ],
    ]);
}

export const MMAssemblyBuffers: IInjectedAssembly = new MMAssembly();
