import { MM_GAME, MM_SAVE, MM_GLOBAL_PTR, MM_PLAYER, MM_ACTOR_POSITION_OFFSET, MM_ACTOR_POSITION_SIZE, MM_ACTOR_ROTATION_OFFSET, MM_ACTOR_ROTATION_SIZE, MM_DUNGEON_ITEM_ADDR } from './MMAliases';
import { OOT_GAME, OOT_SAVE, OOT_GLOBAL_PTR, OOT_PLAYER, OOT_ACTOR_ROTATION_OFFSET, OOT_ACTOR_POSITION_OFFSET, OOT_ACTOR_POSITION_SIZE, OOT_ACTOR_ROTATION_SIZE, OOT_DUNGEON_ITEM_ADDR } from './OotAliases';

export let Z64_GLOBAL_PTR: number;
export let Z64_SAVE: number;
export let Z64_PLAYER: number;
export let Z64_GAME: number;
export let Z64_ACTOR_ROTATION_OFFSET: number;
export let Z64_ACTOR_ROTATION_SIZE: number;
export let Z64_ACTOR_POSITION_OFFSET: number;
export let Z64_ACTOR_POSITION_SIZE: number;
export let Z64_DUNGEON_ITEM_ADDR: number;

export let Z64_IS_RANDOMIZER: boolean;

export function setupOot() {
    Z64_GAME = OOT_GAME;
    Z64_SAVE = OOT_SAVE;
    Z64_GLOBAL_PTR = OOT_GLOBAL_PTR;
    Z64_PLAYER = OOT_PLAYER;
    Z64_ACTOR_ROTATION_OFFSET = OOT_ACTOR_ROTATION_OFFSET;
    Z64_ACTOR_ROTATION_SIZE = OOT_ACTOR_ROTATION_SIZE;
    Z64_ACTOR_POSITION_OFFSET = OOT_ACTOR_POSITION_OFFSET;
    Z64_ACTOR_POSITION_SIZE = OOT_ACTOR_POSITION_SIZE;
    Z64_DUNGEON_ITEM_ADDR = OOT_DUNGEON_ITEM_ADDR;
}

export function setupMM() {
    Z64_GAME = MM_GAME;
    Z64_SAVE = MM_SAVE;
    Z64_GLOBAL_PTR = MM_GLOBAL_PTR;
    Z64_PLAYER = MM_PLAYER;
    Z64_ACTOR_ROTATION_OFFSET = MM_ACTOR_ROTATION_OFFSET;
    Z64_ACTOR_ROTATION_SIZE = MM_ACTOR_ROTATION_SIZE;
    Z64_ACTOR_POSITION_OFFSET = MM_ACTOR_POSITION_OFFSET;
    Z64_ACTOR_POSITION_SIZE = MM_ACTOR_POSITION_SIZE;
    Z64_DUNGEON_ITEM_ADDR = MM_DUNGEON_ITEM_ADDR;
}

export function markAsRandomizer() {
    Z64_IS_RANDOMIZER = true;
}